### ISSUE TITLE
Que tan importante es manejar Expresiones Regulares para un Front?

### ISSUE THREAD

**Issue by cristofer-dev** [cristofer-dev/MyRoadMap#1]
Vale la pena darse el tiempo de aprenderlas en profundidad

**Comment by Xabadu** [comment]
Si y no. Son importantes y un 'nice to have', pero puedes sobrevivir bastante tiempo sin saber crear una de cero, ya que hay n librerías, colecciones y utilidades por ahi, por lo que inicialmente creo q hay otras prioridades en las que te puedes enfocar. Creo que el paso más importante es aprender a entenderlas, para poder ver una y saber que hace cada sección de ellas.

De todas formas, aprender sobre regex es relativamente rápido. Dedicándole una tarde deberías al menos ya manejar los conceptos base. Hay un mini curso de Code School que es super bueno, dura un poco menos de 2 hrs.

Igual es muy probable que pases mucho tiempo sin usarlas y que incluso hayan proyectos en los que ni siquiera las necesites.
