### ISSUE TITLE
JS OOP

### ISSUE THREAD

**Issue by cristofer-dev** [cristofer-dev/MyRoadMap#2]
Que diferencia existen entre la **Forma A** y la **Forma B** (obviando la sintaxis)

**Forma A**
```
class Poligono {
  constructor(alto, ancho) {
    this.alto = alto;
    this.ancho = ancho;
  }
  
  sum(){
    return this.alto + this.ancho
  }

}
```
**Forma B**
```
function Solution(){
    var queue = [];
    var stack = [];
    
    this.pushCharacter=function(ch){
        stack.unshift(ch)
    }
    
    this.enqueueCharacter = function(ch){
        queue.push(ch)
    }
}
```

**Comment by Xabadu** [comment]
La gran diferencia es en términos de herencia, la forma A hace herencia de clases mientras que la B hace herencia a nivel de prototipos, que en realidad más que herencia clásica es composición de objetos.

Con una estructura de clases, todos los objetos creados son iguales y los que heredan, lo hacen de "la misma plantilla", en cambio con composición de objetos, el nuevo que crees puede "heredar" de múltiples objetos que van cambiando a lo largo del tiempo.

Este video es buena referencia para entender composición de objetos y como difiere de la herencia: https://www.youtube.com/watch?v=wfMtDGfHWpA
