### ISSUE TITLE
Buenas Prácticas con CSS

### ISSUE THREAD

**Issue by cristofer-dev** [cristofer-dev/MyRoadMap#3]
Existe Documentación o lineamientos generales para el uso e implementación de **CSS** ?

**Comment by Xabadu** [comment]
Hay un par de metodologías como SMACSS: https://smacss.com/ , pero no son estrictas. Hay algunas buenas prácticas que vas a encontrar en artículos o libros, pero en realidad en cuanto a escribir CSS propiamente tal hay poca flexibilidad en cuan diferente puedes hacerlo.

Si hay n herramientas que puedes usar para hacer tu proceso un poco más cómodo, como pre-procesadores (SASS, LESS, Stylus, etc) o Post-procesadores como PostCSS que te van a ayudar a hacer tus selectores más completos para distintos browsers.

Lo bueno de usar pre o post procesadores es que vas a escribir al estilo que esa herramienta requiere y se va a encargar de hacer toda la transformación para dejarlo más optimizado y ordenado.
