### ISSUE TITLE
Manipulación de cache

### ISSUE THREAD

**Issue by cristofer-dev** [cristofer-dev/MyRoadMap#4]
La duda va principalmente por que cuando se pasa a producción una nueva version y hay cambios en JS o css, esos demoran en la propagación.

Que se sugiere para manipular el cache de los recursos web, js y css principalmente?
¿Qué cabeceras de caché debería usar?  `Expires`, `Cache-Control: max-age` o `Last-Modified`

Quizas forzar la descarga del recurso cambiando el nombre de la url en plan `"my_stylesheet_fingerprint.css"` aunque eso implicaria manipular las rutas en cada paso a producción e igual es un lio.

**Comment by Xabadu** [comment]
Hablemos de nuevo en un par de semanas, porque es justo un problema que estoy viendo actualmente. Por mientras, pegale una mirada a este: https://jakearchibald.com/2016/caching-best-practices/

**Comment by cristofer-dev** [comment]
BKN... voy al link! Thanks!
