### ISSUE TITLE
La carpeta /build en webpack se ignora en git ?

### ISSUE THREAD

**Issue by cristofer-dev** [cristofer-dev/MyRoadMap#5]

**Comment by Xabadu** [comment]
Depende lo que estes desarrollando. Si es un sitio o app y el `/build` es el "compilado" de tu src, si, puedes ignorarlo sin problemas, lo generas antes o durante tu proceso de deploy. Si es una librería y ese build tiene los archivos necesarios para que funcione, entonces no, si no, cada persona que la trate de usar va a tener que generar su propio build, aunque para ese caso es mejor whitelistear los archivos que vas a disponibilizar mediate la opción `files` en tu `package.json`

**Comment by cristofer-dev** [comment]
Ok, entiendo!

Me queda la duda con `whitelistear los archivos` con la opción `files`, nunca la he usado!

**Comment by Xabadu** [comment]
Hay una sección files que se puede agregar al package.json para ver que archivos se incluyen cuando tu paquete se instala como dependencia. Más info: https://docs.npmjs.com/files/package.json#files
