### ISSUE TITLE
Tests en JS 

### ISSUE THREAD

**Issue by cristofer-dev** [cristofer-dev/MyRoadMap#6]
Partiendo de la base que estoy recien leyendo hacerca de TDD, tengo sólo la teoria.

Y quiero empezar a hacer algunos test, que sugieren ... **Jest** ó **Mocha ( con Chai )**, **Jasmin** u otro ?

**Comment by fforres** [comment]
Si es por elegir un framework, Lo mejorcito hoy en dia es Jest.
Pero a fin de cuentas... onda raya pa la suma, el framework termina siendo un plus, pero no lo mas importante, la logica de testeo es mas o menos la misma :)

**Comment by Xabadu** [comment]
^That. Igual te recomendaría Jest para partir, especialmente si estás trabajando en React. Ava es buenísimo también y Tape es muy sencillo de usar/bueno para partir.

Mocha tiene algunos problemas con contaminación de globales cuando estás corriendo una suite grande. Si no limpias los estados después de cada test te puedes encontrar con algunos escenarios complejos de debuggear, pero fuera de eso anda bien.

**Comment by cristofer-dev** [comment]
Son super cool! Gracias!

- [ ] Jest
- [ ] Ava
- [ ] Tape
