### ISSUE TITLE
npm shrinkwrap

### ISSUE THREAD

**Issue by cristofer-dev** [cristofer-dev/MyRoadMap#7]
Para bloquear dependencias ejecuto `npm shrinkwrap` lo que me genera un `npm-shrinkwrap.json`

y con eso ya esta ? o hay que hacer algo mas ??

**Comment by Xabadu** [comment]
Con eso está. La próxima vez que tires un `npm install` va a usare ese `npm-shrinkwrap.json` como referencia para saber que versiones instalar. Cada vez que instales un paquete nuevo eso si, debes correr `npm shrinkwrap` para regenerar ese archivo.

De la misma forma, si estás usando una versión de npm >= 5 va a generar un `package-lock.json` que es 'casi' lo mismo.

Y si usas yarn, al agregar paquetes o instalar por primera vez, generará un `yarn.lock`.
